#!/bin/sh

if [ $# != 2 ]; then
	echo "Usage: $(basename "$0") <day> <gh-cookie>" >&2
	exit 1
fi

if [ ! -d .git ]; then
	echo "Must be run from the repository root" >&2
	exit 1
fi

name="$(printf "aoc%02d" "$1")"
cargo new --bin "$name"
curl --cookie "session=$2" https://adventofcode.com/2021/day/"$1"/input > "$name"/input.txt

